apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: read-only
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-cluster
rules:
- apiGroups: ["","storage.k8s.io","rbac.authorization.k8s.io"]
  verbs: ["get", "list"]
  resources: ["clusterroles","namespaces","persistentvolumes","storageclasses","nodes"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: view-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole 
  name: view-cluster
subjects:
- kind: ServiceAccount
  name: read-only
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-only
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: read-only
  namespace: kube-system
