apiVersion: v1
kind: ReplicationController
metadata:
  name: micro
  labels:
    app: micro
spec:
  replicas: 1
  selector:
    app: micro
  template:
    metadata:
      labels:
        app: micro
    spec:
      containers:
      - name: micro
        image: abcxlab/micro:latest
        ports:
        - containerPort: 8080
          protocol: TCP
      
