apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
  labels:
    app: kubia
spec:
  replicas: 1
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: abcxlab/kubia:latest
        ports:
        - containerPort: 8080
          protocol: TCP
      
